
///////////////////////////////////////////////////////////////////////////////
/// DO NOT EDIT - autogenerated content
///////////////////////////////////////////////////////////////////////////////
namespace Ws.Fus.Strips.Interfaces.Entities
{
    public enum StripType
    {
        eStripNull = 0,
        eStripPrimary = 1,
        eStripSecondary = 2,
        eStripThird = 3,
        eStripPreOpPrimaryMR = 4,
        eStripPreOpSecondaryMR = 5,
        eStripPreOpThirdMR = 6,
        eStripPreOpCT = 7,
        eStripDoseMag = 8,
        eStripCalibrationRoll = 9,        // = 17,
        eStripCalibrationPitch = 10,    // = 18 ,
        eStripCalibrationYaw = 11,        // = 19,
        eStripInitTempMap = 12,
        eStripDoseThermal = 13,            // = 21, // eStripDosePRF
        eStripPostOp = 19,                // = 33,
        eStripMovementDetectRefPrimary = 20,    // = 36,
        eStripMovementDetectRefSecondary = 21,    // = 37,
        eStripMovementDetectRefThird = 22,    // = 38,
        eStripMovementDetectCurPrimary = 23,    // = 39,
        eStripMovementDetectCurSecondary = 24,    // = 40,
        eStripMovementDetectCurThird = 25,    // = 41,
        eStripReconstructedPrimary = 26,    // = 42,
        eStripReconstructedSecondary = 27,    // = 43,
        eStripReconstructedThird = 28,    // = 44,
        eStripLast // must be the last one !

    }
}